Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonitorMicroservice.Models
{
    public class Hospital
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MonitorMicroservice.Models;

namespace MonitorMicroservice.Controllers
{
    public class HospitalController : Controller
    {
        private ApplicationContext db;
        public HospitalController(ApplicationContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await db.Hospitals.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Hospital hospital)
        {
            db.Hospitals.Add(hospital);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Hospital hospital = await db.Hospitals.FirstOrDefaultAsync(p => p.Id == id);
                if (hospital != null)
                    return View(hospital);
            }
            return NotFound();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Hospital hospital = await db.Hospitals.FirstOrDefaultAsync(p => p.Id == id);
                if (hospital != null)
                    return View(hospital);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Hospital hospital)
        {
            db.Hospitals.Update(hospital);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Hospital hospital = await db.Hospitals.FirstOrDefaultAsync(p => p.Id == id);
                if (hospital != null)
                    return View(hospital);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Hospital hospital = new Hospital { Id = id.Value };
                db.Entry(hospital).State = EntityState.Deleted;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

Views/Hospital/Create.cshtml
@model MonitorMicroservice.Models.Hospital
@{
    ViewBag.Title = "Добавление больницы";
}
<form asp-action="create" asp-controller="Hospital">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Полное название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Hospital/Delete.cshtml
@model MonitorMicroservice.Models.Hospital
@{
    ViewBag.Title = "Удаление больницы";
}

<div>
    <dl class="dl-horizontal">
        <dt>Полное наименование</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <div>
        <form asp-controller="Hospital" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

Views/Hospital/Details.cshtml
@model MonitorMicroservice.Models.Hospital
@{
    ViewBag.Title = Model.Name;
}
<h2>Больница @Model.Name</h2>
<div>
    <dl class="dl-horizontal">
        <dt>Идентификатор</dt>
        <dd>@Model.Id</dd>

        <dt>Наименование</dt>
        <dd>@Model.Name</dd>
    </dl>
</div>

Views/Hospital/Edit.cshtml
@model MonitorMicroservice.Models.Hospital
@{
    ViewBag.Title = "Редактирование данных о поликлинике";
}
<form asp-action="edit" asp-controller="Hospital" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Имя</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

Views/Hospital/Index.cshtml
@model IEnumerable<MonitorMicroservice.Models.Hospital>
@{
    ViewBag.Title = "Все больницы";
}
<a asp-action="Create">Добавить больницу</a>
<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>
                <a asp-action="Details" asp-controller="Hospital" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Hospital" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Hospital" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>