Models/Analyzes/Analyse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonitorMicroservice.Models.Analyzes
{
    public class Analyse
    {
        public List<AnalyseBloodBio> AnalyseBloodBio { get; set; }

        public List<AnalyseBloodClynic> AnalyseBloodClynic { get; set; }

        public List<AnalyseBloodGroup> AnalyseBloodGroup { get; set; }

        public List<AnalyseCoprogram> AnalyseCoprogram { get; set; }

        public List<AnalyseIFA> AnalyseIFA { get; set; }

        public List<AnalyseUrine> AnalyseUrine { get; set; }
    }
}

Controllers/AnalyseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MonitorMicroservice.Models;
using MonitorMicroservice.Models.Analyzes;

namespace MonitorMicroservice.Controllers
{
    public class AnalyseController : Controller
    {
        private ApplicationContext db;
        public AnalyseController(ApplicationContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            var model = new Analyse
            {
                AnalyseBloodBio = await db.AnalyzesBloodBio.ToListAsync(),
                AnalyseBloodClynic = await db.AnalyzesBloodClynic.ToListAsync(),
                AnalyseBloodGroup = await db.AnalyzesBloodGroup.ToListAsync(),
                AnalyseCoprogram = await db.AnalyzesCoprogram.ToListAsync(),
                AnalyseIFA = await db.AnalyzesIFA.ToListAsync(),
                AnalyseUrine = await db.AnalyzesUrine.ToListAsync()
            };

            return View(model);
        }

        public async Task<IActionResult> ShowBloodBio()
        {
            return View(await db.AnalyzesBloodBio.ToListAsync());
        }

        public async Task<IActionResult> ShowBloodClynic()
        {
            return View(await db.AnalyzesBloodClynic.ToListAsync());
        }

        public async Task<IActionResult> ShowBloodGroup()
        {
            return View(await db.AnalyzesBloodGroup.ToListAsync());
        }

        public async Task<IActionResult> ShowCoprogram()
        {
            return View(await db.AnalyzesCoprogram.ToListAsync());
        }

        public async Task<IActionResult> ShowIfa()
        {
            return View(await db.AnalyzesIFA.ToListAsync());
        }

        public async Task<IActionResult> ShowUrine()
        {
            return View(await db.AnalyzesUrine.ToListAsync());
        }

        /*public IActionResult Create()
        {
            return View();
        }*/

        public IActionResult CreateBloodBio()
        {
            return View();
        }

        public IActionResult CreateBloodClynic()
        {
            return View();
        }
        public IActionResult CreateBloodGroup()
        {
            return View();
        }
        public IActionResult CreateCoprogram()
        {
            return View();
        }
        public IActionResult CreateIFA()
        {
            return View();
        }
        public IActionResult CreateUrine()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateBloodBio(AnalyseBloodBio analyse)
        {
            db.AnalyzesBloodBio.Add(analyse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateBloodClynic(AnalyseBloodClynic analyse)
        {
            db.AnalyzesBloodClynic.Add(analyse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateBloodGroup(AnalyseBloodGroup analyse)
        {
            db.AnalyzesBloodGroup.Add(analyse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateCoprogram(AnalyseCoprogram analyse)
        {
            db.AnalyzesCoprogram.Add(analyse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateIFA(AnalyseIFA analyse)
        {
            db.AnalyzesIFA.Add(analyse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateUrine(AnalyseUrine analyse)
        {
            db.AnalyzesUrine.Add(analyse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(string type, int? id)
        {
            if (id != null)
            {
                switch (type)
                {
                    case "blood-bio":
                        AnalyseBloodBio bloodBio = await db.AnalyzesBloodBio.FirstOrDefaultAsync(p => p.Id == id);
                        if (bloodBio != null)
                            return View(bloodBio);
                        break;
                    case "blood-clynic":
                        AnalyseBloodClynic bloodClynic = await db.AnalyzesBloodClynic.FirstOrDefaultAsync(p => p.Id == id);
                        if (bloodClynic != null)
                            return View(bloodClynic);
                        break;
                    case "blood-group":
                        AnalyseBloodGroup bloodGroup = await db.AnalyzesBloodGroup.FirstOrDefaultAsync(p => p.Id == id);
                        if (bloodGroup != null)
                            return View(bloodGroup);
                        break;
                    case "coprogram":
                        AnalyseCoprogram coprogram = await db.AnalyzesCoprogram.FirstOrDefaultAsync(p => p.Id == id);
                        if (coprogram != null)
                            return View(coprogram);
                        break;
                    case "ifa":
                        AnalyseIFA ifa = await db.AnalyzesIFA.FirstOrDefaultAsync(p => p.Id == id);
                        if (ifa != null)
                            return View(ifa);
                        break;
                    case "urine":
                        AnalyseUrine urine = await db.AnalyzesUrine.FirstOrDefaultAsync(p => p.Id == id);
                        if (urine != null)
                            return View(urine);
                        break;
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Edit(string type, int? id)
        {
            if (id != null)
            {
                switch (type)
                {
                    case "blood-bio":
                        AnalyseBloodBio bloodBio = await db.AnalyzesBloodBio.FirstOrDefaultAsync(p => p.Id == id);
                        if (bloodBio != null)
                            return View(bloodBio);
                        break;
                    case "blood-clynic":
                        AnalyseBloodClynic bloodClynic = await db.AnalyzesBloodClynic.FirstOrDefaultAsync(p => p.Id == id);
                        if (bloodClynic != null)
                            return View(bloodClynic);
                        break;
                    case "blood-group":
                        AnalyseBloodGroup bloodGroup = await db.AnalyzesBloodGroup.FirstOrDefaultAsync(p => p.Id == id);
                        if (bloodGroup != null)
                            return View(bloodGroup);
                        break;
                    case "coprogram":
                        AnalyseCoprogram coprogram = await db.AnalyzesCoprogram.FirstOrDefaultAsync(p => p.Id == id);
                        if (coprogram != null)
                            return View(coprogram);
                        break;
                    case "ifa":
                        AnalyseIFA ifa = await db.AnalyzesIFA.FirstOrDefaultAsync(p => p.Id == id);
                        if (ifa != null)
                            return View(ifa);
                        break;
                    case "urine":
                        AnalyseUrine urine = await db.AnalyzesUrine.FirstOrDefaultAsync(p => p.Id == id);
                        if (urine != null)
                            return View(urine);
                        break;
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AnalyseBloodBio analyseBloodBio)
        {
            db.AnalyzesBloodBio.Update(analyseBloodBio);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AnalyseBloodClynic analyseBloodClynic)
        {
            db.AnalyzesBloodClynic.Update(analyseBloodClynic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AnalyseBloodGroup analyseBloodGroup)
        {
            db.AnalyzesBloodGroup.Update(analyseBloodGroup);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AnalyseCoprogram analyseCoprogram)
        {
            db.AnalyzesCoprogram.Update(analyseCoprogram);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AnalyseIFA analyseIfa)
        {
            db.AnalyzesIFA.Update(analyseIfa);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AnalyseUrine analyseUrine)
        {
            db.AnalyzesUrine.Update(analyseUrine);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(string type, int? id)
        {
            if (id != null)
            {
                switch (type)
                {
                    case "blood-bio":
                        AnalyseBloodBio bloodBio = new AnalyseBloodBio { Id = id.Value };

Views/Analyse/CreateBloodBio.cshtml
@model MonitorMicroservice.Models.Analyzes.AnalyseBloodBio
@{
    ViewBag.Title = "Добавление биохимичекого анализа крови";
}
<form asp-action="CreateBloodBio" asp-controller="Analyse">
    <div class="form-group">
        <label asp-for="PatientId" class="control-label">ID пациента</label>
        <input type="text" asp-for="PatientId" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Analyse/CreateBloodClynic.cshtml
@model MonitorMicroservice.Models.Analyzes.AnalyseBloodClynic
@{
    ViewBag.Title = "Добавление биохимичекого анализа крови";
}
<form asp-action="CreateBloodClynic" asp-controller="Analyse">
    <div class="form-group">
        <label asp-for="PatientId" class="control-label">ID пациента</label>
        <input type="text" asp-for="PatientId" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Hemoglobin" class="control-label">Гемоглобин</label>
        <input type="text" asp-for="Hemoglobin" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Erythrocyte" class="control-label">Эритроциты</label>
        <input type="text" asp-for="Erythrocyte" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Leukocyte" class="control-label">Лейкоциты</label>
        <input type="text" asp-for="Leukocyte" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Platelet" class="control-label">Тромбоциты</label>
        <input type="text" asp-for="Platelet" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Analyse/CreateBloodGroup.cshtml
@model MonitorMicroservice.Models.Analyzes.AnalyseBloodGroup
@{
    ViewBag.Title = "Добавление биохимичекого анализа крови";
}
<form asp-action="CreateBloodGroup" asp-controller="Analyse">
    <div class="form-group">
        <label asp-for="PatientId" class="control-label">ID пациента</label>
        <input type="text" asp-for="PatientId" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Analyse/CreateCoprogram.cshtml
@model MonitorMicroservice.Models.Analyzes.AnalyseCoprogram
@{
    ViewBag.Title = "Добавление биохимичекого анализа крови";
}
<form asp-action="CreateCoprogram" asp-controller="Analyse">
    <div class="form-group">
        <label asp-for="PatientId" class="control-label">ID пациента</label>
        <input type="text" asp-for="PatientId" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Analyse/CreateIFA.cshtml
@model MonitorMicroservice.Models.Analyzes.AnalyseIFA
@{
    ViewBag.Title = "Добавление биохимичекого анализа крови";
}
<form asp-action="CreateIFA" asp-controller="Analyse">
    <div class="form-group">
        <label asp-for="PatientId" class="control-label">ID пациента</label>
        <input type="text" asp-for="PatientId" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Analyse/CreateUrine.cshtml
@model MonitorMicroservice.Models.Analyzes.AnalyseUrine
@{
    ViewBag.Title = "Добавление биохимичекого анализа крови";
}
<form asp-action="CreateUrine" asp-controller="Analyse">
    <div class="form-group">
        <label asp-for="PatientId" class="control-label">ID пациента</label>
        <input type="text" asp-for="PatientId" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Analyse/Index.cshtml
<!--<a asp-action="CreateBloodBio">Добавить биохимический анализ крови</a>
<a asp-action="CreateBloodClynic">Добавить клинический анализ крови</a>
<a asp-action="CreateBloodGroup">Добавить анализ группы крови</a>
<a asp-action="CreateCoprogram">Добавить копрограмму</a>
<a asp-action="CreateIFA">Добавить ИФА-диагностику</a>
<a asp-action="CreateUrine">Добавить общий анализ мочи</a>-->


@{
    ViewBag.Title = "Все анализы";
}

@model MonitorMicroservice.Models.Analyzes.Analyse
<a asp-action="CreateBloodBio">Добавить биохимический анализ крови</a>
<table class="table">
    <tr>
        <th>ID анализа</th>
        <th>ID пациента</th>
        <th>Операции</th>
    </tr>

    @foreach (var item in Model.AnalyseBloodBio)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.PatientId</td>
            <td>
                <a asp-action="Details" asp-controller="Analyse" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Analyse" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Analyse" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>

<a asp-action="CreateBloodClynic">Добавить клинический анализ крови</a>
<table class="table">
    <tr>
        <th>ID анализа</th>
        <th>ID пациента</th>
        <th>Операции</th>
    </tr>

    @foreach (var item in Model.AnalyseBloodClynic)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.PatientId</td>
            <td>
                <a asp-action="Details" asp-controller="Analyse" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Analyse" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Analyse" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>

<a asp-action="CreateBloodGroup">Добавить анализ группы крови</a>
<table class="table">
    <tr>
        <th>ID анализа</th>
        <th>ID пациента</th>
        <th>Операции</th>
    </tr>

    @foreach (var item in Model.AnalyseBloodGroup)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.PatientId</td>
            <td>
                <a asp-action="Details" asp-controller="Analyse" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Analyse" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Analyse" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>

<a asp-action="CreateCoprogram">Добавить копрограмму</a>
<table class="table">
    <tr>
        <th>ID анализа</th>
        <th>ID пациента</th>
        <th>Операции</th>
    </tr>
    @foreach (var item in Model.AnalyseCoprogram)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.PatientId</td>
            <td>
                <a asp-action="Details" asp-controller="Analyse" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Analyse" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Analyse" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>

<a asp-action="CreateIFA">Добавить ИФА-диагностику</a>
<table class="table">
    <tr>
        <th>ID анализа</th>
        <th>ID пациента</th>
        <th>Операции</th>
    </tr>

    @foreach (var item in Model.AnalyseIFA)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.PatientId</td>
            <td>
                <a asp-action="Details" asp-controller="Analyse" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Analyse" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Analyse" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>

<a asp-action="CreateUrine">Добавить общий анализ мочи</a>
<table class="table">
    <tr>
        <th>ID анализа</th>
        <th>ID пациента</th>
        <th>Операции</th>
    </tr>

    @foreach (var item in Model.AnalyseUrine)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.PatientId</td>
            <td>
                <a asp-action="Details" asp-controller="Analyse" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Analyse" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Analyse" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>